# Generated by Django 4.0.4 on 2022-06-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='postcode',
            field=models.CharField(default='E34 4PF', max_length=7),
            preserve_default=False,
        ),
    ]
